[Options]
#验证码超时时间，单位为分钟数
Verifycodetimeout = 5
ServerPort = ":9999"
Secret = "Monibuca#!4"
HostName = "http://localhost:9999"
[Mysql]
Server = "sh-cynosdbmysql-grp-kxt43lv6.sql.tencentcdb.com:28520"
Username = "root"
Password = "Monibuca#!4"
Database = "monibuca"
[Mail]
SMTPserver = "smtp.exmail.qq.com"
SMTPport = ":465"
SMTPusername = "service@monibuca.com"
SMTPpassword = "Gcgm35TT7nZ4HrT4"
#SMTPusername = "pg@monibuca.com"
#SMTPpassword = "LjDAxkuV3hQBBkHY"
SMTPshowname = "m7s"