name: console build

on:
  create:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare release environment
    runs-on: ubuntu-latest
    steps:
      - run: env
  build-gui:
    name: Build gui
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows/amd64
            output: console.exe
          - os: macos-latest
            platform: darwin/universal
            output: console
          - os: ubuntu-latest
            platform: linux/amd64
            output: console-linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup pnpm    
        run: npm install -g pnpm

      - name: wails build
        # uses: dAppServer/wails-build-action@v2            
        uses: dwdcth/wails-build-action@v2.0.4
        with:
          app-working-directory: ./wails
          build-name: ${{ matrix.output }}
          build-platform: ${{ matrix.platform }}
          go-version: 1.20.x
          package: false
          
      # - name: macos act
      #   if: runner.os == 'macOS'
      #   shell: bash
      #   run: |
      #     cd wails
      #     rm -rf ./build/bin/${{ matrix.output }}.app.zip
      #     ditto -c -k --keepParent ./build/bin/${{matrix.output}}.app ./build/bin/${{matrix.output}}.app.zip
      #     rm -rf ./build/bin/${{ matrix.output }}.app

      - name: upload atrifact
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: wails/build/bin/*

  collect-release:
    name: Collect and release
    needs: [build-gui]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch commit messages since last release
        run: |
          # Get current tag
          current_tag=$(git describe --tags --abbrev=0)
          
          # Get previous tag (latest one before the current one)
          previous_commit=$(git rev-list --tags --skip=1 --max-count=1)
          previous_tag=$(git describe --abbrev=0 --tags ${previous_commit})
          
          # List commits between the previous and current tag
          commit_messages=$(git log --pretty=format:"- [%s](https://github.com/${{ github.repository }}/commit/%H)" ${previous_tag}..${current_tag})

          # Save commit messages to an output file
          echo "$commit_messages" > commits.txt
          echo "Commit messages since last release:" 
          cat commits.txt
          echo commit_messages_path=$(pwd)/commits.txt >> $GITHUB_ENV
        shell: bash

      - name: download
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      
      - name: rename   
        working-directory: target
        run: |
          ls -al 
          rm -rf console-amd64-installer.exe
          rm -rf console.pkg
          cp console.app.zip console_mac_amd64.zip
          cp console.app.zip console_mac_arm64.zip
          zip console_windows_amd64.zip console.exe
          zip console_linux_amd64.zip console-linux
          rm  -rf console_linux console.exe console.app.zip


      # release assets
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*
          body_path: ${{ env.commit_messages_path }}

      - name: scp
        uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          host: console.monibuca.com
          user: root
          key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
          local: "target/*"
          remote: /usr/local/nginx/html/mb/dist/download
          scp_options: -v       