# inside .github/workflows/action.yml
name: Add File to Bucket
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: create file
        run: |
          mkdir releases
          touch a.txt b.txt
      - name: Upload file to bucket
        uses: koraykoska/s3-upload-github-action@master
        env:
          FILE: ./releases/
          S3_ENDPOINT: ' ${{ secrets.S3_ID }}.r2.cloudflarestorage.com'
          S3_BUCKET: monibuca
          S3_ACCESS_KEY_ID: ${{ secrets.S3_API }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}